<?php
/**
 * 
 * Table metadata for the Proxima_Model_Tags model class.
 * 
 * This class is auto-generated by make-model; any changes you make will be
 * overwritten the next time you use make-model.  Modify the Proxima_Model_Tags
 * class instead of this one.
 * 
 */
class Proxima_Model_Tags_Metadata extends Proxima_Sql_Model_Metadata
{
    public $table_name = 'tags';
    
    public $table_cols = array (
      'id' => array (
        'name' => 'id',
        'type' => 'int',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => true,
        'autoinc' => true,
      ),
      'name' => array (
        'name' => 'name',
        'type' => 'varchar',
        'size' => 255,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => false,
        'autoinc' => false,
      ),
      'descr' => array (
        'name' => 'descr',
        'type' => 'varchar',
        'size' => 255,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
    );
    
    public $index_info = array (
      'name' => array (
        'type' => 'unique',
        'cols' => array (
          0 => 'name',
        ),
      ),
    );
}
