<?php
/**
 * 
 * Table metadata for the Proxima_Model_Nodes model class.
 * 
 * This class is auto-generated by make-model; any changes you make will be
 * overwritten the next time you use make-model.  Modify the Proxima_Model_Nodes
 * class instead of this one.
 * 
 */
class Proxima_Model_Nodes_Metadata extends Proxima_Sql_Model_Metadata
{
    public $table_name = 'nodes';
    
    public $table_cols = array (
      'id' => array (
        'name' => 'id',
        'type' => 'int',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => true,
        'primary' => true,
        'autoinc' => true,
      ),
      'created' => array (
        'name' => 'created',
        'type' => 'timestamp',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'updated' => array (
        'name' => 'updated',
        'type' => 'timestamp',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'inherit' => array (
        'name' => 'inherit',
        'type' => 'varchar',
        'size' => 32,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'publish' => array (
        'name' => 'publish',
        'type' => 'timestamp',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'slug' => array (
        'name' => 'slug',
        'type' => 'varchar',
        'size' => 255,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'member_handle' => array (
        'name' => 'member_handle',
        'type' => 'varchar',
        'size' => 32,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'parent_id' => array (
        'name' => 'parent_id',
        'type' => 'int',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'uri' => array (
        'name' => 'uri',
        'type' => 'varchar',
        'size' => 255,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'status' => array (
        'name' => 'status',
        'type' => 'varchar',
        'size' => 32,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'pos' => array (
        'name' => 'pos',
        'type' => 'int',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'subj' => array (
        'name' => 'subj',
        'type' => 'varchar',
        'size' => 255,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'summ' => array (
        'name' => 'summ',
        'type' => 'clob',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
      'body' => array (
        'name' => 'body',
        'type' => 'clob',
        'size' => NULL,
        'scope' => NULL,
        'default' => NULL,
        'require' => false,
        'primary' => false,
        'autoinc' => false,
      ),
    );
    
    public $index_info = array (
      'created' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'created',
        ),
      ),
      'updated' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'updated',
        ),
      ),
      'publish' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'publish',
        ),
      ),
      'name' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'slug',
        ),
      ),
      'parent_id' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'parent_id',
        ),
      ),
      'owner_handle' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'member_handle',
        ),
      ),
      'inherit' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'inherit',
        ),
      ),
      'pos' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'pos',
        ),
      ),
      'uri' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'uri',
        ),
      ),
      'status' => array (
        'type' => 'normal',
        'cols' => array (
          0 => 'status',
        ),
      ),
    );
}
